import type { NextPage } from "next";
import Head from "next/head";
import { TimerComponent } from "../components/Timer";

const Home: NextPage = () => {
  return (
    <div className="flex h-full w-full flex-col bg-black pb-4">
      <Head>
        <title>rubik-scramble</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          media="screen"
          href="https://fontlibrary.org//face/segment7"
          type="text/css"
        />
      </Head>
      <TimerComponent />
      {/* <nav className="flex justify-center gap-4 py-4 font-mono lowercase text-white">
        <Link href="/">
          <a className="rounded-md px-2 py-1 hover:bg-zinc-800">Timer</a>
        </Link>
        <Link href="/timer">
          <a className="rounded-md px-2 py-1 hover:bg-zinc-800">Stats</a>
        </Link>
        <Link href="/timer">
          <a className="rounded-md px-2 py-1 hover:bg-zinc-800">Settings</a>
        </Link>
        <Link href="/timer">
          <a className="rounded-md px-2 py-1 hover:bg-zinc-800">Help</a>
        </Link>
      </nav> */}
    </div>
  );
};

export default Home;
